# disease_map.py

DISEASE_DISPLAY_MAP = {
    "apple_black_rot": "Apple - Black Rot",
    "apple_healthy": "Apple - Healthy",
    "apple_mosaic_virus": "Apple - Mosaic Virus",
    "apple_rust": "Apple - Rust",
    "apple_scab": "Apple - Scab",
    "banana_anthracnose": "Banana - Anthracnose",
    "banana_black_streak": "Banana - Black Streak",
    "banana_bunchy_top": "Banana - Bunchy Top",
    "banana_cigar_end_rot": "Banana - Cigar End Rot",
    "banana_cordana_spot": "Banana - Cordana Spot",
    "banana_panama_disease": "Banana - Panama Disease",
    "blueberry_anthracnose": "Blueberry - Anthracnose",
    "blueberry_botrytis_blight": "Blueberry - Botrytis Blight",
    "blueberry_healthy": "Blueberry - Healthy",
    "blueberry_mummy_berry": "Blueberry - Mummy Berry",
    "blueberry_rust": "Blueberry - Rust",
    "blueberry_scorch": "Blueberry - Scorch",
    "cherry_healthy": "Cherry - Healthy",
    "cherry_powdery_ mildew": "Cherry - Powdery Mildew",
    "cherry_spot": "Cherry - Spot",
    "citrus_canker": "Citrus - Canker",
    "citrus_greening_disease": "Citrus - Greening Disease",
    "corn_blight": "Corn - Blight",
    "corn_gray_spot": "Corn - Gray Spot",
    "corn_healthy": "Corn - Healthy",
    "corn_rust": "Corn - Rust",
    "corn_smut": "Corn - Smut",
    "grape_black_rot": "Grape - Black Rot",
    "grape_downy_mildew": "Grape - Downy Mildew",
    "grape_esca_(black_measles)": "Grape - Esca (Black Measles)",
    "grape_healthy": "Grape - Healthy",
    "grape_leaf_blight_(isariopsis_leaf_spot)": "Grape - Leaf Blight (Isariopsis Leaf Spot)",
    "grape_roll_disease": "Grape - Roll Disease",
    "grape_spot": "Grape - Spot",
    "peach_anthracnose": "Peach - Anthracnose",
    "peach_bacterial_spot": "Peach - Bacterial Spot",
    "peach_brown_rot": "Peach - Brown Rot",
    "peach_curl": "Peach - Curl",
    "peach_healthy": "Peach - Healthy",
    "peach_rust": "Peach - Rust",
    "peach_scab": "Peach - Scab",
    "pepper_bell_blossom_end_rot": "Pepper (Bell) - Blossom End Rot",
    "pepper_bell_frogeye_spot": "Pepper (Bell) - Frogeye Spot",
    "pepper_bell_healthy": "Pepper (Bell) - Healthy",
    "pepper_bell_powdery_mildew": "Pepper (Bell) - Powdery Mildew",
    "pepper_bell_spot": "Pepper (Bell) - Spot",
    "potato_early_blight": "Potato - Early Blight",
    "potato_healthy": "Potato - Healthy",
    "potato_late_blight": "Potato - Late Blight",
    "raspberry_fire_blight": "Raspberry - Fire Blight",
    "raspberry_gray_mold": "Raspberry - Gray Mold",
    "raspberry_healthy": "Raspberry - Healthy",
    "raspberry_spot": "Raspberry - Spot",
    "raspberry_yellow_rust": "Raspberry - Yellow Rust",
    "soybean_bacterial_blight": "Soybean - Bacterial Blight",
    "soybean_brown_spot": "Soybean - Brown Spot",
    "soybean_downy_mildew": "Soybean - Downy Mildew",
    "soybean_frog_eye_spot": "Soybean - Frog Eye Spot",
    "soybean_healthy": "Soybean - Healthy",
    "soybean_mosaic": "Soybean - Mosaic",
    "soybean_rust": "Soybean - Rust",
    "squash_bacterial_wilt": "Squash - Bacterial Wilt",
    "squash_downy_mildew": "Squash - Downy Mildew",
    "squash_powdery_mildew": "Squash - Powdery Mildew",
    "squash_yellow_mosaic_virus": "Squash - Yellow Mosaic Virus",
    "strawberry_anthracnose": "Strawberry - Anthracnose",
    "strawberry_healthy": "Strawberry - Healthy",
    "strawberry_scorch": "Strawberry - Scorch",
    "tomato_bacterial_spot": "Tomato - Bacterial Spot",
    "tomato_early_blight": "Tomato - Early Blight",
    "tomato_healthy": "Tomato - Healthy",
    "tomato_late_blight": "Tomato - Late Blight",
    "tomato_mold": "Tomato - Mold",
    "tomato_mosaic_virus": "Tomato - Mosaic Virus",
    "tomato_septoria_spot": "Tomato - Septoria Spot",
    "tomato_target_spot": "Tomato - Target Spot",
    "tomato_two_spotted_spider_mites": "Tomato - Two Spotted Spider Mites",
    "tomato_yellow_virus": "Tomato - Yellow Virus (Leaf Curl)",
    "wheat_bacterial_streak_black_chaff": "Wheat - Bacterial Streak Black Chaff",
    "wheat_head_scab": "Wheat - Head Scab",
    "wheat_leaf_rust": "Wheat - Leaf Rust",
    "wheat_loose_smut": "Wheat - Loose Smut",
    "wheat_powdery_mildew": "Wheat - Powdery Mildew",
    "wheat_septoria_blotch": "Wheat - Septoria Blotch",
    "wheat_stem_rust": "Wheat - Stem Rust",
    "wheat_stripe_rust": "Wheat - Stripe Rust"
}